name: CI

on:
  push:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code source via une action Github existante
        uses: actions/checkout@v3

      - name: Installer les dep
        run: npm ci

      - name: Dit bonjour
        run: echo "Hello Elioris world"
