name: CI

on:
  push:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code source via une action Github existante
        uses: actions/checkout@v3

      - name: Installer les dep
        run: npm ci

      - name: Lance les tests
        run: npm test

      - name: Lint code
        run: npm run lint

      - name: Génération d'artifact dans dist/ avec action upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Dit bonjour
        run: echo "Hello Elioris world"
